excluded:
  - AppDelegate
  - Resources/Generated

function_parameter_count:
  warning: 6
  error: 11 

line_length: 145

identifier_name:
  min_length:
    warning: 2
    error: 2

file_length:
    warning: 300
